AllCops:
  Include:
    - Rakefile
  Exclude:
    - test.rb
    - bin/**


SpecialGlobalVars:
  Enabled: false

PerlBackrefs:
  Enabled: false

Documentation:
  Enabled: false

BlockComments:
  Enabled: false

Encoding:
  Enabled: false

MultilineBlockChain:
  Enabled: false

RegexpLiteral:
  Enabled: false

# dots at the end of lines are okay
DotPosition:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 20

ParameterLists:
  Max: 5
  CountKeywordArgs: true

BlockNesting:
  Max: 4

CollectionMethods:
  PreferredMethods:
    map: 'collect'
    map!: 'collect!'
    reduce: 'inject'
    detect: 'find'
    find_all: 'select'

CaseIndentation:
  IndentWhenRelativeTo: end
  IndentOneStep: true

ClassLength:
  Max: 150

LineLength:
  Enabled: false

# Personally, I prefer to outdent public/protected/private, as it makes
# it easier to see the different sections of code.
AccessModifierIndentation:
  EnforcedStyle: outdent

EmptyLinesAroundAccessModifier:
  Enabled: true

EndAlignment:
  AlignWith: variable

Metrics/AbcSize:
  Max: 19

Style/DoubleNegation:
  Enabled: false

SpaceInsideBrackets:
  Enabled: false

PercentLiteralDelimiters:
  Enabled: false

BarePercentLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/FileName:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

